services:
  - type: web
    name: netflix-login-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    plan: free
